
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jan 30 19:25:39 CET 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INCREMENT = 41;
  public static final int CONST = 28;
  public static final int GE = 35;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 25;
  public static final int DECREMENT = 42;
  public static final int FOR = 23;
  public static final int MINUS = 15;
  public static final int RPAREN = 7;
  public static final int AND = 26;
  public static final int LT = 34;
  public static final int OR = 27;
  public static final int COMMA = 8;
  public static final int DIV = 17;
  public static final int PLUS = 11;
  public static final int IF = 39;
  public static final int DOT = 22;
  public static final int LE = 36;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 12;
  public static final int TRUE = 29;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int MUL = 16;
  public static final int NUMBER = 37;
  public static final int MOD = 18;
  public static final int IDENT = 38;
  public static final int BREAK = 24;
  public static final int VOID = 13;
  public static final int EQ = 31;
  public static final int ELSE = 40;
  public static final int LBRACE = 3;
  public static final int LSQUARE = 20;
  public static final int READ = 14;
  public static final int CHARCONST = 43;
  public static final int RSQUARE = 21;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int NE = 32;
  public static final int FALSE = 30;
  public static final int GT = 33;
  public static final int PRINT = 9;
}

